name: Backup Firestore

on:
  schedule:
  - cron: '0 0 * * *'
    displayName: Daily midnight build

env:
  PROJECT_ID: magisterkasensory
  BUCKET: gs://backup-student

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.BACKUP_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - run: gcloud config set project $PROJECT_ID
      - run: gcloud firestore export $BUCKET